import './sass/main.scss';
// import './js/practice/practice1';
// import './js/practice/practice2';
// import './js/practice/practice3';
// import './js/practice/practice4';
// import './js/practice/practice5';
// import './js/practice/practice6';
// import './js/practice/practice7';
// import './js/practice/practice8';
// import './js/practice/lection8-add';
// import './js/practice/practice8-add';
// import './js/practice/practice9';
// import './js/practice/practice10';
// import './js/practice/practice11';
// import './js/practice/practice17';
// import './js/practice/practice18';
// import './js/practice/ObjectAssign-polyfill';
// import './js/apps/game';
// import './js/app/bookshelf';
// import './js/app/timer';
// import './js/movies';
// import './js/food-service';
// import './js/apps/events';
// import './js/training/array-flat-polyfill';
// import './js/training/findstring';
// import './js/apps/pixabay';
import './js/training/loadGrain';
