import './sass/main.scss';
// import './js/practice1';
import './js/practice2';
// import './js/practice3';
// import './js/practice4';
// import './js/practice5';
// import './js/practice6';
// import './js/practice7';
// import './js/practice8';
// import './js/lection8-add';
// import './js/practice8-add';
// import './js/practice9';
import './js/practice10';
